src/Entity/Guestentry.php
<?php

namespace App\Entity;

use App\Repository\GuestentryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GuestentryRepository::class)
 */
class Guestentry
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="guestentries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_on;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified_on;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="guestentries")
     */
    private $modified;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getModifiedOn(): ?\DateTimeInterface
    {
        return $this->modified_on;
    }

    public function setModifiedOn(?\DateTimeInterface $modified_on): self
    {
        $this->modified_on = $modified_on;

        return $this;
    }

    public function getModified(): ?User
    {
        return $this->modified;
    }

    public function setModified(?User $modified): self
    {
        $this->modified = $modified;

        return $this;
    }
}

src/Form/GuestentryType.php
<?php

namespace App\Form;

use App\Entity\Guestentry;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
class GuestentryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ['attr' => ['class' => 'form-control']])
            ->add('image', FileType::class, ['attr' => ['class' => 'form-control']])
            ->add('created_on',DateTimeType::class, ['attr' => ['class' => 'form-control']])
            ->add('status',ChoiceType::class, ['attr' => ['class' => 'form-control'], 'choices'  => [
                        'Select' => null,
                        'Approved' => 1,
                        'Rejected' => 0,
                    ]])
            //->add('modified_on')
            //->add('user')
            //->add('modified')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Guestentry::class,
        ]);
    }
}

src/Controller/GuestentryController.php
<?php

namespace App\Controller;

use App\Entity\Guestentry;
use App\Form\GuestentryType;
use App\Repository\GuestentryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/guestentry")
 */
class GuestentryController extends AbstractController
{
    /**
     * @Route("/", name="app_guestentry_index", methods={"GET"})
     */
    public function index(GuestentryRepository $guestentryRepository): Response
    {
        return $this->render('guestentry/index.html.twig', [
            'guestentries' => $guestentryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_guestentry_new", methods={"GET", "POST"})
     */
    public function new(Request $request, GuestentryRepository $guestentryRepository): Response
    {
        $guestentry = new Guestentry();
        $form = $this->createForm(GuestentryType::class, $guestentry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->get('security.token_storage')->getToken()->getUser();
            //$id = $user->getUserIdentifier();

            $guestentry->setUser($user);
            $guestentryRepository->add($guestentry, true);

            return $this->redirectToRoute('app_guestentry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('guestentry/new.html.twig', [
            'guestentry' => $guestentry,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_guestentry_show", methods={"GET"})
     */
    public function show(Guestentry $guestentry): Response
    {
        return $this->render('guestentry/show.html.twig', [
            'guestentry' => $guestentry,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_guestentry_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Guestentry $guestentry, GuestentryRepository $guestentryRepository): Response
    {
        $form = $this->createForm(GuestentryType::class, $guestentry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $guestentryRepository->add($guestentry, true);

            return $this->redirectToRoute('app_guestentry_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('guestentry/edit.html.twig', [
            'guestentry' => $guestentry,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_guestentry_delete", methods={"POST"})
     */
    public function delete(Request $request, Guestentry $guestentry, GuestentryRepository $guestentryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$guestentry->getId(), $request->request->get('_token'))) {
            $guestentryRepository->remove($guestentry, true);
        }

        return $this->redirectToRoute('app_guestentry_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/guestentry/_delete_form.html.twig
<form method="post" action="{{ path('app_guestentry_delete', {'id': guestentry.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ guestentry.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/guestentry/_form.html.twig
<div class="row">
        <div class="col-lg-12 align-center">
          
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

</div>
</div>

templates/guestentry/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Guestentry{% endblock %}

{% block body %}
    <h1>Edit Guestentry</h1>

    {{ include('guestentry/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_guestentry_index') }}" class="btn btn-small">back to list</a>

    {{ include('guestentry/_delete_form.html.twig') }}
{% endblock %}

templates/guestentry/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guestentry index{% endblock %}

{% block body %}
   
    <div class="row">
        <div class="col-lg-12 align-center">
           <h2>Guestentry index</h2>
           <div class="col-lg-12">
              <div class="panel">
                <div class="panel-content">      
                  <div class="row">
                    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Image</th>
                <th>Created_on</th>
                <th>Status</th>
                <th>Modified_on</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for guestentry in guestentries %}
            <tr>
                <td>{{ guestentry.id }}</td>
                <td>{{ guestentry.title }}</td>
                <td>{{ guestentry.image }}</td>
                <td>{{ guestentry.createdOn ? guestentry.createdOn|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ guestentry.status }}</td>
                <td>{{ guestentry.modifiedOn ? guestentry.modifiedOn|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_guestentry_show', {'id': guestentry.id}) }}">show</a>
                    <a href="{{ path('app_guestentry_edit', {'id': guestentry.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    <a href="{{ path('app_guestentry_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/guestentry/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Guestentry{% endblock %}

{% block body %}
    <h1>Create new Guestentry</h1>

    {{ include('guestentry/_form.html.twig') }}

    <a href="{{ path('app_guestentry_index') }}">back to list</a>
{% endblock %}

templates/guestentry/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guestentry{% endblock %}

{% block body %}
    <h1>Guestentry</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ guestentry.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ guestentry.title }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ guestentry.image }}</td>
            </tr>
            <tr>
                <th>Created_on</th>
                <td>{{ guestentry.createdOn ? guestentry.createdOn|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ guestentry.status }}</td>
            </tr>
            <tr>
                <th>Modified_on</th>
                <td>{{ guestentry.modifiedOn ? guestentry.modifiedOn|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_guestentry_index') }}" class="btn btn-small">Back to list</a>

    <a href="{{ path('app_guestentry_edit', {'id': guestentry.id}) }}" class="btn btn-small">Edit</a>

    {{ include('guestentry/_delete_form.html.twig') }}
{% endblock %}